<a href="https://colab.research.google.com/github/YasirAhmadX/DL/blob/main/DL_lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# DeepLearning Lab1
MLP introduction

**yasir ahmad**  
**22MIA1064**

-read data  
-feature extration  
-training model  
-testing

## Read Data

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('dataset.csv');
df

Text  Label
0                            The movie is good.      1
1                             The movie is bad.      0
2  The acting skills of the actor is fantastic.      1
3             The story and screenplay was poor      0
4                       The story was excellent      1

In [10]:
t = df['Text'].values
l = df['Label'].values
t

array(['The movie is good.', 'The movie is bad.',
       'The acting skills of the actor is fantastic.',
       'The story and screenplay was poor', 'The story was excellent'],
      dtype=object)

In [11]:
l

array([1, 0, 1, 0, 1])

## Feature Extraction

In [12]:
t,l

(array(['The movie is good.', 'The movie is bad.',
        'The acting skills of the actor is fantastic.',
        'The story and screenplay was poor', 'The story was excellent'],
       dtype=object),
 array([1, 0, 1, 0, 1]))

### CountVectorizer

In [31]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split

cv = CountVectorizer()
f = cv.fit_transform(t)

print(f)

  (0, 14)	1
  (0, 8)	1
  (0, 7)	1
  (0, 6)	1
  (1, 14)	1
  (1, 8)	1
  (1, 7)	1
  (1, 3)	1
  (2, 14)	2
  (2, 7)	1
  (2, 0)	1
  (2, 12)	1
  (2, 9)	1
  (2, 1)	1
  (2, 5)	1
  (3, 14)	1
  (3, 13)	1
  (3, 2)	1
  (3, 11)	1
  (3, 15)	1
  (3, 10)	1
  (4, 14)	1
  (4, 13)	1
  (4, 15)	1
  (4, 4)	1


### TfidfVectorizer

In [30]:
from sklearn.feature_extraction.text import TfidfVectorizer

vt = TfidfVectorizer()
ft = vt.fit_transform(t)

print(ft)

  (0, 14)	0.31240462919759415
  (0, 8)	0.5289470171197818
  (0, 7)	0.43907380594868767
  (0, 6)	0.6556161938708753
  (1, 14)	0.31240462919759415
  (1, 8)	0.5289470171197818
  (1, 7)	0.43907380594868767
  (1, 3)	0.6556161938708753
  (2, 14)	0.3779901241486624
  (2, 7)	0.2656259653502091
  (2, 0)	0.3966273597667837
  (2, 12)	0.3966273597667837
  (2, 9)	0.3966273597667837
  (2, 1)	0.3966273597667837
  (2, 5)	0.3966273597667837
  (3, 14)	0.2239091933513975
  (3, 13)	0.37911121942437037
  (3, 2)	0.4698985847130067
  (3, 11)	0.4698985847130067
  (3, 15)	0.37911121942437037
  (3, 10)	0.4698985847130067
  (4, 14)	0.299642119521264
  (4, 13)	0.5073382098444343
  (4, 15)	0.5073382098444343
  (4, 4)	0.6288326342298832


## MLP

In [37]:
from sklearn.neural_network import MLPClassifier

ml = MLPClassifier()

ml.fit(f,l)

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPClassifier()

In [56]:
s1 = ["The movie was not bad"]
st1 = cv.transform(s1)

ml.predict(st1)

array([0])

In [57]:
s2 = ["The movie was not good"]
st2 = cv.transform(s2)

ml.predict(st2)

array([1])

In [58]:
s3 = ["The movie is good"]
st3 = cv.transform(s3)

ml.predict(st3)

array([1])

## Implement the same using
* SVM
* Naive_Bayes
* Random Forest

### SVM

In [52]:
from sklearn.svm import SVC

svc = SVC()
svc.fit(f,l)

SVC()

In [82]:
print(s1)
print(svc.predict(st1))

print(s2)
print(svc.predict(st2))

print(s3)
print(svc.predict(st3))

['The movie was not bad']
[1]
['The movie was not good']
[1]
['The movie is good']
[1]


### Naive Bayes

In [74]:
from sklearn.naive_bayes import MultinomialNB

nb = MultinomialNB()
nb.fit(f, l)

MultinomialNB()

In [80]:
print(s1)
print(nb.predict(st1))

print(s2)
print(nb.predict(st2))

print(s3)
print(nb.predict(st3))

['The movie was not bad']
[0]
['The movie was not good']
[1]
['The movie is good']
[1]


### Random Forest

In [60]:
from sklearn.ensemble import RandomForestClassifier

rfc = RandomForestClassifier()
rfc.fit(f,l)

RandomForestClassifier()

In [79]:
print(s1)
print(rfc.predict(st1))

print(s2)
print(rfc.predict(st2))

print(s3)
print(rfc.predict(st3))

['The movie was not bad']
[0]
['The movie was not good']
[1]
['The movie is good']
[1]
